In [14]:
#loading a csv file
import pandas as pd
data=pd.read_csv('Mainflow task-2.csv')
data.head(4)

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
0,31-00:00,23.10,16.520,121.717,1177.607,169.805,358.282,329.545,1.443,599.253,...,67.122,329.432,303.099,175.964,1127.197,1319.039,257.325,54.612,252.077,NaN
1,31-01:00,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,...,60.012,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.11
2,31-02:00,23.19,16.709,79.562,1329.407,239.161,350.022,329.260,1.600,549.611,...,61.304,329.140,303.383,164.013,677.534,1327.072,237.272,51.795,251.335,NaN
3,31-03:00,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,...,68.496,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.02

In [15]:
data.columns

Index(['Observation', 'Y-Kappa', 'ChipRate', 'BF-CMratio', 'BlowFlow',
       'ChipLevel4 ', 'T-upperExt-2 ', 'T-lowerExt-2  ', 'UCZAA',
       'WhiteFlow-4 ', 'AAWhiteSt-4 ', 'AA-Wood-4  ', 'ChipMoisture-4 ',
       'SteamFlow-4 ', 'Lower-HeatT-3', 'Upper-HeatT-3 ', 'ChipMass-4 ',
       'WeakLiquorF ', 'BlackFlow-2 ', 'WeakWashF ', 'SteamHeatF-3 ',
       'T-Top-Chips-4 ', 'SulphidityL-4 '],
      dtype='object')

In [3]:
#filtering
ykappa_filter=data[data['Y-Kappa'] > 24]
ykappa_filter.head(4)

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
1,31-01:00,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,...,60.012,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.110
9,31-08:00,24.70,13.850,96.208,1334.892,362.511,352.372,327.358,1.515,553.172,...,64.249,332.264,305.419,166.120,909.810,1318.725,180.375,48.842,251.121,29.210
11,31-10:00,24.40,14.117,85.998,1330.104,394.234,348.089,319.027,1.429,540.558,...,62.179,329.831,302.652,163.258,827.107,1312.372,132.163,49.446,251.406,29.292
12,31-11:00,26.62,15.467,84.447,1334.255,386.971,349.392,321.021,1.428,531.250,...,59.407,330.284,303.248,156.797,799.947,1299.782,118.901,46.597,251.721,NaN

In [4]:
#filtering
chiprate_filter=data[data['ChipRate']<15]
chiprate_filter.head(4)

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
6,1-09:00,13.49,13.700,98.186,1243.688,116.275,346.208,326.982,1.434,696.766,...,72.989,322.982,296.080,182.018,784.281,929.527,201.272,58.118,248.741,NaN
7,31-06:00,22.65,14.100,91.887,1307.852,288.989,352.321,331.162,1.468,625.549,...,71.298,329.662,301.539,179.886,837.178,1315.111,234.047,53.805,249.971,29.22
8,31-07:00,22.50,14.233,97.249,1346.900,330.325,352.687,328.894,1.480,591.827,...,68.791,331.485,303.488,174.804,889.516,1317.912,226.319,52.546,250.414,NaN
9,31-08:00,24.70,13.850,96.208,1334.892,362.511,352.372,327.358,1.515,553.172,...,64.249,332.264,305.419,166.120,909.810,1318.725,180.375,48.842,251.121,29.21

In [9]:
#filtering
blowflow_filter = data[(data['BlowFlow'] >= 1250) & (data['BlowFlow'] <= 1300)]
blowflow_filter.head(4)

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
14,31-13:00,24.05,16.675,77.025,1284.386,246.336,350.317,329.240,1.538,537.811,...,58.979,329.560,302.146,160.587,823.039,1300.545,372.228,51.740,251.492,NaN
35,1-10:00,12.17,12.667,114.570,1253.584,188.043,350.765,332.170,1.440,683.410,...,76.147,328.278,302.245,162.915,537.597,984.720,51.967,53.475,249.036,30.23
48,1-23:00,19.20,15.736,80.975,1274.247,197.078,343.644,321.692,1.577,628.652,...,64.060,319.501,296.922,164.721,682.528,996.502,233.945,50.544,251.640,NaN
49,2-00:00,17.80,15.708,81.625,1282.194,186.236,346.299,323.116,1.561,664.611,...,66.848,319.853,297.387,170.228,722.687,997.741,0.000,53.741,251.243,30.30

In [13]:
#filtering
sulphidity_filter = data[data['SulphidityL-4 '].notnull()]
sulphidity_filter.head(4)

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
1,31-01:00,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,...,60.012,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.11
3,31-03:00,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,...,68.496,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.02
4,31-04:00,22.90,15.618,93.244,1334.168,243.131,351.640,332.709,NaN,638.672,...,70.022,328.352,300.954,183.929,888.448,1343.424,215.372,54.186,249.916,29.01
5,1-08:00,14.23,15.350,85.518,1171.604,198.538,344.014,325.195,1.436,628.245,...,65.225,322.103,298.517,165.814,826.243,907.641,595.875,52.807,249.580,30.34

In [17]:
#missing values
missing_values = data.isnull().sum()
missing_values

Observation          0
Y-Kappa              0
ChipRate             5
BF-CMratio          17
BlowFlow            16
ChipLevel4           1
T-upperExt-2         2
T-lowerExt-2         2
UCZAA               25
WhiteFlow-4          1
AAWhiteSt-4        151
AA-Wood-4            1
ChipMoisture-4       1
SteamFlow-4          1
Lower-HeatT-3        2
Upper-HeatT-3        2
ChipMass-4           1
WeakLiquorF          1
BlackFlow-2          2
WeakWashF            1
SteamHeatF-3         2
T-Top-Chips-4        1
SulphidityL-4      151
dtype: int64

In [20]:
#filling the missing values with mean
fill = data.fillna(data.mean(numeric_only=True))
fill.head(5)

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
0,31-00:00,23.10,16.520,121.717,1177.607,169.805,358.282,329.545,1.44300,599.253,...,67.122,329.432,303.099,175.964,1127.197,1319.039,257.325,54.612,252.077,30.411671
1,31-01:00,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.54900,537.201,...,60.012,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.110000
2,31-02:00,23.19,16.709,79.562,1329.407,239.161,350.022,329.260,1.60000,549.611,...,61.304,329.140,303.383,164.013,677.534,1327.072,237.272,51.795,251.335,30.411671
3,31-03:00,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.60400,623.362,...,68.496,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.020000
4,31-04:00,22.90,15.618,93.244,1334.168,243.131,351.640,332.709,1.49201,638.672,...,70.022,328.352,300.954,183.929,888.448,1343.424,215.372,54.186,249.916,29.010000

In [21]:
#summary statisitcs
summary=data.describe()
summary

,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,AAWhiteSt-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
count,324.000000,319.000000,307.000000,308.000000,323.000000,322.000000,322.000000,299.000000,323.000000,173.000000,...,323.000000,322.000000,322.000000,323.000000,323.000000,322.000000,323.000000,322.000000,323.000000,173.000000
mean,20.635370,14.347937,87.464456,1237.837614,258.164483,356.904295,324.020180,1.492010,591.732260,6.140410,...,66.668285,325.567820,300.525699,162.222322,873.828941,1175.917016,263.543068,49.696907,251.240087,30.411671
std,3.070036,1.499095,7.995012,100.593735,87.987452,9.209290,7.621402,0.105923,67.016351,0.081609,...,5.708587,4.609862,4.568484,14.160688,122.073521,149.334010,163.666942,4.551909,1.283432,0.701317
min,12.170000,9.983000,68.645000,0.000000,0.000000,339.168000,284.633000,1.182000,405.111000,5.890000,...,48.568000,318.051000,293.312000,113.922000,486.938000,838.948000,0.000000,35.510000,248.359000,29.010000
25%,18.382500,13.358000,81.823000,1193.215250,213.527000,350.241250,321.420000,1.431500,540.989500,6.089000,...,62.518000,321.385500,296.513250,153.032500,792.019500,1044.817500,134.649000,46.389750,250.312000,29.970000
50%,20.845000,14.308000,86.739000,1273.138500,271.792000,356.843000,325.669000,1.498000,592.895000,6.135000,...,67.429000,324.741000,299.126000,163.690000,865.254000,1150.221500,269.193000,50.277000,251.380000,30.370000
75%,23.032500,15.517000,92.372000,1289.196000,321.680000,362.242250,329.175000,1.560500,639.480500,6.199000,...,71.522000,329.845250,304.244750,172.555000,965.286500,1319.021250,405.563000,53.294250,252.323500,30.820000
max,27.600000,16.958000,121.717000,1351.240000,419.014000,399.135000,337.012000,1.747000,731.394000,6.340000,...,76.147000,333.854000,311.146000,189.268000,1226.277000,1395.767000,715.715000,63.332000,254.122000,32.840000